language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: "52.0"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower
- bower install
script: xvfb-run npm test
cache:
  directories:
    - node_modules
